# Generated by Django 6.0 on 2025-12-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Cloud', 'Cloud'), ('CI/CD', 'CI/CD'), ('Monitoring', 'Monitoring'), ('Security', 'Security'), ('IaC', 'Infrastructure as Code'), ('Scripting', 'Scripting'), ('Container', 'Container Orchestration'), ('OS', 'Operating System'), ('Build', 'Build'), ('Web', 'Web/Proxy')], default='Cloud', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tools', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
