# Generated by Django 6.0 on 2025-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(related_name='projects', to='portfolio.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('devops', 'DevOps'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon_path',
            field=models.CharField(help_text='Path relative to static/image/tools/', max_length=200),
        ),
    ]
