# Generated by Django 6.0 on 2025-12-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('containerization', 'Containerization'), ('orchestration', 'Orchestration'), ('ci_cd', 'CI/CD'), ('iac', 'Infrastructure as Code'), ('cloud', 'Cloud'), ('version_control', 'Version Control'), ('configuration', 'Configuration'), ('monitoring', 'Monitoring'), ('security', 'Security'), ('programming', 'Programming'), ('web_server', 'Web Server'), ('scripting', 'Scripting'), ('build', 'Build'), ('artifacts', 'Artifacts'), ('os', 'Operating System'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(help_text='Brief description of the tool')),
                ('icon_url', models.CharField(help_text='Static path like /static/image/tools/terraform.png', max_length=255)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for the tool sphere', max_length=7)),
                ('link', models.URLField(blank=True, help_text='Optional link to tool website')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
