# Generated by Django 6.0 on 2026-01-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_file',
            field=models.ImageField(blank=True, help_text='Upload featured image directly (recommended: 1200x630)', null=True, upload_to='articles/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload project icon (recommended: 64x64 or 128x128)', null=True, upload_to='projects/icons/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload project image directly', null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload skill icon directly (recommended: 64x64 or 128x128 PNG)', null=True, upload_to='skills/icons/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload tool icon directly (recommended: 128x128 PNG)', null=True, upload_to='tools/icons/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='External image URL (optional)'),
        ),
    ]
