# Generated by Django 6.0 on 2026-01-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Display this project on the homepage'),
        ),
    ]
